# fly.toml app configuration file generated for moria on 2023-11-17T18:11:57-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "moria"
primary_region = "iad"
kill_signal = "SIGTERM"

[build]

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "app.gokept.com"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
